import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Todos } from "../components/src/components/Todos/Todos";
import { CreateUser } from "../components/src/components/welcomePage/CreateUser";
import { HomeDashboard } from "../components/src/components/homeDashboard/HomeDashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeDashboard />
      </main>
    </>
  );
}
